# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py2exe.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(629, 185)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 30, 491, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line_load_file = QtWidgets.QLineEdit(self.frame)
        self.line_load_file.setGeometry(QtCore.QRect(90, 10, 299, 22))
        self.line_load_file.setObjectName("line_load_file")
        self.label_load_file = QtWidgets.QLabel(self.frame)
        self.label_load_file.setGeometry(QtCore.QRect(8, 8, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_load_file.setFont(font)
        self.label_load_file.setObjectName("label_load_file")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(390, 9, 77, 56))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_load_file = QtWidgets.QPushButton(self.widget)
        self.btn_load_file.setObjectName("btn_load_file")
        self.verticalLayout.addWidget(self.btn_load_file)
        self.btn_exec = QtWidgets.QPushButton(self.widget)
        self.btn_exec.setObjectName("btn_exec")
        self.verticalLayout.addWidget(self.btn_exec)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(Dialog)
        self.line_load_file.returnPressed.connect(Dialog.return_pressed_slot)
        self.btn_load_file.clicked.connect(Dialog.load_file_slot)
        self.btn_exec.clicked.connect(Dialog.execute_program_slot)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_load_file.setText(_translate("Dialog", "Source File"))
        self.btn_load_file.setText(_translate("Dialog", "Load File"))
        self.btn_exec.setText(_translate("Dialog", "Convert"))
        self.label_title.setText(_translate("Dialog", "PY-2-EXE Converter Tool"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
